spring:
  jpa:
    hibernate:
      ddl-auto: none
      database: MYSQL
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
  datasource:
    url: jdbc:mysql://192.168.80.129:3306/test?characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true&useCursorFetch=true
    username: root
    password:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 192.168.80.131:9300
      repositories:
        enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.191.1:8081/eureka/
