spring:
  jpa:
    hibernate:
      ddl-auto: none
      database: MYSQL
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password:
#  datasource:
#    url: jdbc:mysql://touchtv0primary.mysql.rds.aliyuncs.com:3306/touchtv?characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
#    username: touchtv
#    password: TV!@#$%^0924
  redis:
    host: 192.168.31.49
    port: 6379
    password:
    pool:
      maxActive: 8
      maxWait: -1
      maxIdle: 8
      minIdle: 0
      timeout: 0
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


spring.data.elasticsearch.cluster-name: itouchtv
spring.data.elasticsearch.cluster-nodes : 172.18.0.20:9300,172.18.16.12:9300
spring.data.elasticsearch.repositories.enabled : true
search.elasticsearch.enabled: true